name: Account CI

on: [ push ]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew :test --tests *
     
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: echo "hello" >> hello.txt 
    - uses: actions/cache@v2
      with:
        path: hello.txt
        key: ${{ runner.os }}-hello-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-hello-
  
  hello:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - uses: actions/cache@v2
      with:
        path: hello.txt
        key: ${{ runner.os }}-hello-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-hello-
    - run: cat hello.txt
  Build:

    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/
        key: ${{ runner.os }}-code-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-code-
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew build
