name: Account CI

on: [ push ]

jobs:     
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ./*
        key: code-${{ github.sha }}

  Build:

    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - uses: actions/cache@v2
      with:
        path: ./*
        key: code-${{ github.sha }}
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: gradle-dependencies-${{ hashFiles('**/*.gradle') }}
        restore-keys: gradle-dependencies-
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew compileJava
    - run: ./gradlew test
