name: Account CI

on: [ push ]

jobs:     
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache code
      uses: actions/cache@v2
      with:
        path: |
          ./*
          !./docker
          !./.github
          !./.git
          !./.gitignore
        key: code-${{ github.sha }}

  build:
    runs-on: ubuntu-latest
    
    needs: [checkout]
    
    steps:
    - name: Cache code
      uses: actions/cache@v2
      with:
        path: |
          ./*
          !./docker
          !./.github
          !./.git
          !./.gitignore
        key: code-${{ github.sha }}-build
        restore-keys: code-${{ github.sha }}
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew compileJava compileTestJava
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Cache code
      uses: actions/cache@v2
      with:
        path: |
          ./*
          !./docker
          !./.github
          !./.git
          !./.gitignore
        key: code-${{ github.sha }}-build
        restore-keys: code-${{ github.sha }}
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests application
      run: ./gradlew test
