name: Account CI

on: [ push ]

jobs:     
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache code
      uses: actions/cache@v2
      with:
        path: |
          ./*
          !./docker
          !./.github
        key: code-${{ github.sha }}
    - run: ls

  build:
    runs-on: ubuntu-latest
    
    needs: [checkout]
    
    steps:
    - name: Cache code
      uses: actions/cache@v2
      with:
        path: |
          ./*
          !./docker
          !./.github
        key: code-${{ github.sha }}
    - run: ls
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ./.gradle/*
        key: gradle-dependencies-${{ hashFiles('**/*.gradle') }}
        restore-keys: gradle-dependencies-
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew compileJava
    - name: Run tests application
      run: ./gradlew test
