name: Account CI

on: [ push ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/
        key: ${{ runner.os }}-code
        restore-keys: |
          ${{ runner.os }}-code
    
  Build:

    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/
        key: ${{ runner.os }}-code
        restore-keys: |
          ${{ runner.os }}-code
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew build
  
  run-tests:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/
        key: ${{ runner.os }}-code
        restore-keys: |
          ${{ runner.os }}-code
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build application
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew :test --tests *
