name: Account CI

on: [ push ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build application
      run: ./gradlew build
  
  run-tests:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew test --tests *
